config:
  name: Spring cloud configurations Based on application
  description: Spring cloud configuration successfully implemented based on application
db:
  connection-string: connection string
  host: 127.0.0.1
  port: 4500