config:
  name: Spring cloud latest configurations Based on application
  description: Spring cloud latest configuration successfully implemented based on application
db:
  connection-string: connection string
  host: 127.0.0.1
  port: 4500
management.endpoints.web.exposure.include: "*"